title: "Arvind’s Blog"
description: "Thoughts, notes, and stories ✨"
theme: jekyll-theme-cayman

show_downloads: false

# Add custom CSS
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/style.css"

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Poetry"
    url: /poetry/
