title: "Blog where science meets stories, neurons meet words."
description: "Thoughts, notes, and stories ✨"
theme: null   # disable default Jekyll theme

show_downloads: false

include:
  - assets/css/style.css
