title: "Arvind’s Blog"
description: "Thoughts, notes, and stories ✨"
theme: jekyll-theme-cayman

# Optional settings for style
show_downloads: false
plugins:
  - jekyll-remote-theme

# Add custom CSS
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/style.css"


